sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 123
    access-key-secret: 123456
    bucket-name: name
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: xxx
    secret: yyy
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: 123456